### ISSUE TITLE
Add component sections/shortcuts feature

### ISSUE THREAD

**Issue by bglw** [CloudCannon/bookshop#104]
Often page builders have to make a choice between exposing "fine" components to the editor (`title`, `button`) or exposing "coarse" components to the editor (`landing-page-hero`, `two-column-product-info`).

A useful Bookshop feature would be the ability to build a "Section" to your array structures, which is a pre-configured set of fine components that could then be edited further. In this world the editor would select `landing-page-hero`, and added to the page would be (for example):

```yaml
- _bookshop_name: two-columns
  left_column:
    - _bookshop_name: title
      # ... 
    - _bookshop_name: button
      # ...
  right_column:
    - _bookshop_name: image
      # ... 
```

At which point the editor could go in and add/remove/edit the "fine" components. This saves them having to crate these page sections by hand, but retains the full control if desired. 

I _think_ this can be implemented acceptably without CMS work. Bookshop can create an array structure, which outputs a structure matching `two-columns` in this example. Once added, the editor would not see the `landing-page-hero` component referenced at all, so perhaps it's more of a shortcut than a section.
