### ISSUE TITLE
Thought experiment: Fields conditional on structure key

### ISSUE THREAD

**Issue by bglw** [CloudCannon/bookshop#106]
Workshopping flexible components, picturing a component definition like the following:

```yaml
# hero.bookshop.yml
spec:
  structures:
    - content_blocks

blueprint:
  title: Hello World
  alignment: Left
```

Available as a nested component:

```yaml
# wrapper.bookshop.yml
spec:
  structures:
    - content_blocks

blueprint:
  blocks: ["bookshop:structure:content_blocks"]
  alignment: Left
```

In this example, the `alignment` key might not make sense to exist on both components. To resolve this, one could imagine a hypothetical syntax:

```yaml
# hero.bookshop.yml
spec:
  structures:
    - structure: content_blocks
    - structure: inner_blocks
      ignore_fields:
        - alignment

blueprint:
  title: Hello World
  alignment: Left
```

Available as a nested component:

```yaml
# wrapper.bookshop.yml
spec:
  structures:
    - content_blocks

blueprint:
  blocks: ["bookshop:structure:inner_blocks"]
  alignment: Left
```

In this world, the hero component would have the `alignment` key when used as a top level component in a `content_blocks` array, but this key would be absent when used in an `inner_blocks` array.

Theoretically, something along these lines could be achieved with an input config of `type: hidden`, assuming a similar capability of defining `_inputs` per structure key. This would provide a key that exists in the data but is not shown to editors, but that doesn't solve the case where one would like the key to be absent altogether.

Overall this needs more thought, but this puts together some of my current brain-scratchings.
