### ISSUE TITLE
Adding description to a component spec removes the label from the editor UI

### ISSUE THREAD

**Issue by ecupaio** [CloudCannon/bookshop#138]
**Version Info**  
Jekyll 4.2.1
"@bookshop/browser": "3.3.0"
"@bookshop/jekyll-engine": "3.3.0"
"@bookshop/live": "3.3.0"
"@bookshop/generate": "3.3.0"

**What I'm Doing**
I'm adding a label and description to my component specs so that users can see the title of the component they will add and a description of what it is. 
```
spec: 
  structures:
  - content_blocks
  label: "Donation - 1 column"
  description: "1 column layout of the donation section."
  icon:
  tags: []
```
**What I Expect**
When I select Add component on the editor, I expect to at least see the title of the component I want to select. 

**What's Happening** 
I see only the truncated description: 
![Screen Shot 2023-03-21 at 12 08 12 PM](https://user-images.githubusercontent.com/7784563/226715699-1371323f-e2c8-40e8-ad8c-71e57707bc38.png)

I notice if I remove the description, the title will show, but that's just a hacky workaround.

**Comment by bglw** [comment]
👋 Hi Ed! Thanks for the report. 

It turns out this is actually a visual bug on the CMS side — this UI is truncating the component label when the description is too long, rather than vice versa. You can see what I mean here:

<img width="307" alt="Screen Shot 2023-03-23 at 6 01 24 PM" src="https://user-images.githubusercontent.com/40188355/227107936-396ef700-5877-4e24-ab56-0e3e2b2f05ac.png">

I'll chase this up as a bug internally and report back here when fixed.

Another fix that is less of a hacky workaround, and often just a good idea in general, is to use the modal component picker. If you add the following to your `cloudcannon.config.yml`: _(or equivalent config to an equivalent file)_

```yml
_structures:
  content_blocks:
    style: modal
```

Then you'll pick components from a modal rather than a dropdown, which doesn't exhibit the same bug. Might be good at least as a temporary measure until we get this fixed up 🙂

**Comment by ecupaio** [comment]
I found that modal setting on the Hydra theme template so that actually works better for my purposes, but my issue still remains that the description wasn’t even truncated, it was absent. Perhaps it didn't like the dash ¯\_(ツ)_/¯

It's a separate issue (please don't go stackoverflow on me. i can open a separate issue if necessary), but I'm not getting a preview despite having the settings configured: 
```
spec: 
  structures:
  - content_blocks
  label: "Basic hero"
  description: 'Title section that goes at the top of a page. Image is optional.'
  icon:
  tags: []
  
blueprint: 
  title: ""
  image: ""

preview:
  title: "Page heading"
  image: "/img/about-hero.jpg"

_inputs: 
  title: 
    type: text
  image: 
    type: image 
```
I did everything [according to the docs](https://github.com/CloudCannon/bookshop/blob/main/guides/jekyll.adoc#component-preview), but it's showing blanks.
