### ISSUE TITLE
Make it possible for a component to have a wrapper class

### ISSUE THREAD

**Issue by Robbie-Cook** [CloudCannon/bookshop#22]
It would be great if we could have a custom wrapper for a single component if we want.

I think others would be interested in this too.

In traditional storybook this is something I do quite a lot. For example, for a `full-width` button, I want to have a wrapper class to demonstrate that the button is bigger.

Maybe this is something we could add to [meta]?

e.g.

```toml
[meta]
wrapper = """

<div class="big-iron"></div>

"""
```

And styles can be defined in `.storybook/styles.scss`.

Any thoughts @bglw ?
