### ISSUE TITLE
Functionality to reference another group of components inside a component schema

### ISSUE THREAD

**Issue by Yoda-Soda** [CloudCannon/bookshop#54]
Currently the component browser does not render/recognise nested array structures.

**Comment by bglw** [comment]
Do you have an example TOML file that isn't showing the correct behavior?

**Comment by bglw** [comment]
To enable the following component pattern:

```toml
# wrapper.bookshop.toml
[props]
content_blocks = [. . .] # Array of components tagged as the `content_blocks` structure
```

Ideally, this flow would provide some functionality in the component browser but would leave the field empty for the CMS to use the existing structure definitions.
